/**
 * `@vectojs/tex` — Zero-DOM TeX math typesetting.
 *
 * A vendored KaTeX parse/layout kernel plus a self-contained SVG emit layer,
 * producing an SVG string that carries its own glyph outlines and references
 * nothing outside itself. That constraint is the reason this package exists:
 * `SVGEntity` rasterizes via `data URI -> Image -> createImageBitmap ->
 * drawImage`, and an `Image` loaded from a data URI resolves no external
 * references and inherits no page CSS, so neither KaTeX's HTML/CSS output nor
 * any webfont-based approach can be used.
 *
 * ## Phase 1 status
 *
 * This is a prototype and the package is `private`. It proves the path from TeX
 * to a self-contained SVG and measures the result; it is not yet wired into
 * `@vectojs/markdown`. See `vectojs-docs/forge/decisions/math-engine-2026-08.md`
 * for the decision and its measurements.
 *
 * ```ts
 * import { layout, emitSVG } from '@vectojs/tex';
 *
 * const { svg, width, height, depth } = emitSVG(layout('x^2 + y^2 = z^2'));
 * ```
 *
 * ## What is vendored and what is ours
 *
 * - `src/kernel/` is KaTeX (MIT), copied by `scripts/vendor-katex.ts` from a
 *   pinned commit and mechanically stripped of MathML and DOM emission. It is
 *   not reformatted or lint-fixed, so it stays diffable against upstream.
 * - `src/registry/` is two hand-written files (`defineFunction`,
 *   `defineEnvironment`) that a token-level transform cannot produce, because
 *   `mathmlBuilder` appears there in expression position.
 * - `src/emit/` and `src/layout.ts` are ours.
 * - `src/glyphs/glyphs.subset.json` is generated by `scripts/generate-glyphs.ts`
 *   (TTF outlines to SVG paths) and narrowed by `scripts/subset-glyphs.ts`.
 */

export {
  type EmitOptions,
  type EmitResult,
  emitSVG,
  type GlyphPlacement,
  KATEX_FONT_SCALE,
} from './emit/svg';
export { type FontName, type ResolvedFont, resolveFont, sizingRatio } from './emit/fonts';
export {
  type Glyph,
  getGlyph,
  shippedFonts,
  shippedGlyphCount,
  UNITS_PER_EM,
} from './emit/glyphTable';
export { layout, type LayoutOptions } from './layout';
