const esbuild = require('esbuild');
const fs = require('fs');
const path = require('path');
const prettier = require('prettier');

const workerPath = path.join(__dirname, '../src/MarkdownWorker.ts');
const outputPath = path.join(__dirname, '../src/MarkdownWorkerSource.ts');

async function buildWorker() {
  const result = esbuild.buildSync({
    entryPoints: [workerPath],
    bundle: true,
    minify: true,
    write: false,
    format: 'iife',
  });

  const minifiedCode = result.outputFiles[0].text;
  const tsContent = `// Automatically generated by scripts/build-worker.js. Do not edit.
export const WORKER_SOURCE_STRING = ${JSON.stringify(minifiedCode)};
`;

  const formattedContent = await prettier.format(tsContent, {
    parser: 'typescript',
    singleQuote: true,
  });
  fs.writeFileSync(outputPath, formattedContent);
  console.log('Worker minified and embedded to MarkdownWorkerSource.ts successfully.');
}

buildWorker().catch((err) => {
  console.error('Failed to build worker:', err);
  process.exit(1);
});
