const esbuild = require('esbuild');
const fs = require('fs');
const path = require('path');

const workerPath = path.join(__dirname, '../src/layout/LayoutWorker.ts');
const outputPath = path.join(__dirname, '../src/layout/LayoutWorkerSource.ts');

try {
  const result = esbuild.buildSync({
    entryPoints: [workerPath],
    bundle: true,
    minify: true,
    write: false,
    format: 'iife',
  });

  const minifiedCode = result.outputFiles[0].text;
  const tsContent = `// Automatically generated by scripts/build-worker.js. Do not edit.
export const WORKER_SOURCE_STRING = ${JSON.stringify(minifiedCode)};
`;

  fs.writeFileSync(outputPath, tsContent);
  console.log('Worker minified and embedded to LayoutWorkerSource.ts successfully.');
} catch (err) {
  console.error('Failed to build worker:', err);
  process.exit(1);
}
