// @vitest-environment node
import { test, expect } from 'vitest';
import { buildSync } from 'esbuild';
import { format } from 'prettier';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { WORKER_SOURCE_STRING } from '../src/LayoutWorkerSource';

/**
 * Worker-bundle freshness check.
 *
 * `src/LayoutWorkerSource.ts` is a committed, minified bundle of
 * `src/LayoutWorker.ts` generated by `scripts/build-worker.js`, and the build
 * regenerates it — but nothing failed when someone edited the worker source and
 * forgot to rebuild, shipping a worker that silently disagreed with the
 * main-thread copy of `computeMSDFLayout`. This test re-runs the exact
 * generation pipeline (same esbuild options, same prettier formatting) in
 * memory and demands byte equality with the committed blob, so a stale bundle
 * fails CI instead of drifting.
 */
test('LayoutWorkerSource matches a fresh build of LayoutWorker', async () => {
  const here = path.dirname(fileURLToPath(import.meta.url));
  const workerPath = path.join(here, '../src/LayoutWorker.ts');

  const result = buildSync({
    entryPoints: [workerPath],
    bundle: true,
    minify: true,
    write: false,
    format: 'iife',
  });
  const minifiedCode = result.outputFiles[0]!.text;

  const regenerated = await format(
    `// Automatically generated by scripts/build-worker.js. Do not edit.\nexport const WORKER_SOURCE_STRING = ${JSON.stringify(minifiedCode)};\n`,
    { parser: 'typescript', singleQuote: true },
  );

  const committedPath = path.join(here, '../src/LayoutWorkerSource.ts');
  const committed = readFileSync(committedPath, 'utf8');

  // Byte equality with what the generator would write today.
  expect.soft(committed).toBe(regenerated);
  // Independent of formatting: the embedded code itself must match a fresh
  // esbuild run, so real drift still fails even if prettier output ever shifts.
  expect.soft(WORKER_SOURCE_STRING).toBe(minifiedCode);
});
